export const FONTWEIGHT_ATTRIBUTE = 'data-font-weight'
export const FONTSTYLE_ATTRIBUTE = 'data-font-style'
export const INLINECODE_ATTRIBUTE = 'data-inline-code'
export const UNDERLINED_ATTRIBUTE = 'data-text-underlined'
export const LINETHROUGH_ATTRIBUTE = 'data-text-linethrough'
